export const CountryList = [
  {
    countyName: "India-English",
    countyCode: "en-IN",
    keyCode: 1,
    prefix: "₹",
    extraKey: 1,
  },
  {
    countyName: "India-Gujarati",
    countyCode: "gu-IN",
    keyCode: 2,
    extraKey: 1,
  },
  { countyName: "India-Hindi", countyCode: "hi-IN", keyCode: 3, extraKey: 1 },
  { countyName: "India-Marathi", countyCode: "mr-IN", keyCode: 4, extraKey: 1 },
  { countyName: "Bangladesh", countyCode: "en-BD", keyCode: 5, prefix: "৳" },
  { countyName: "France", countyCode: "fr-FR", keyCode: 6, prefix: "€" },
  { countyName: "Ghana", countyCode: "en-GH", keyCode: 7, prefix: "gh¢" },
  { countyName: "Iran", countyCode: "fa-IR", keyCode: 8, prefix: "IRR" },
  { countyName: "Mauritius", countyCode: "en-MU", keyCode: 9, prefix: "MUR" },
  { countyName: "Myanmar", countyCode: "en-MM", keyCode: 10, prefix: "MMK" },
  { countyName: "Nigeria", countyCode: "en-NG", keyCode: 11, prefix: "NGN" },
  { countyName: "Turkey", countyCode: "tr-TR", keyCode: 12, prefix: "TRY" },
  { countyName: "UK", countyCode: "en-GB", keyCode: 13, prefix: "£" },
  { countyName: "USA", countyCode: "en-US", keyCode: 14, prefix: "$" },
];
export const currencyListNumber = [
  {
    CtryNm: "FRANCE",
    CurrencyName: "Euro",
    Ccy: "EUR",
    CcyNbr: "978",
    CcyMnrUnts: "2",
    prefix: "€",
    keyCode: 6,
    countyCode: "fr-FR",
  },
  {
    CtryNm: "GHANA",
    CurrencyName: "Ghana Cedi",
    Ccy: "GHS",
    CcyNbr: "936",
    CcyMnrUnts: "2",
    prefix: "gh¢",
    keyCode: 7,
    countyCode: "en-GH",
  },
  {
    CtryNm: "INDIA",
    CurrencyName: "Indian Rupee",
    Ccy: "INR",
    CcyNbr: "356",
    CcyMnrUnts: "2",
    prefix: "₹",
    keyCode: 1,
    countyCode: "en-IN",
  },
  {
    CtryNm: "IRAN (ISLAMIC REPUBLIC OF)",
    CurrencyName: "Iranian Rial",
    Ccy: "IRR",
    CcyNbr: "364",
    CcyMnrUnts: "2",
    prefix: "IRR",
    keyCode: 8,
    countyCode: "fa-IR",
  },
  {
    CtryNm: "MYANMAR",
    CurrencyName: "Kyat",
    Ccy: "MMK",
    CcyNbr: "104",
    CcyMnrUnts: "2",
    prefix: "MMK",
    keyCode: 10,
    countyCode: "en-MM",
  },
  {
    CtryNm: "MAURITIUS",
    CurrencyName: "Mauritius Rupee",
    Ccy: "MUR",
    CcyNbr: "480",
    CcyMnrUnts: "2",
    prefix: "MUR",
    keyCode: 9,
    countyCode: "en-MU",
  },
  {
    CtryNm: "NIGERIA",
    CurrencyName: "Naira",
    Ccy: "NGN",
    CcyNbr: "566",
    CcyMnrUnts: "2",
    prefix: "NGN",
    keyCode: 11,
    countyCode: "en-NG",
  },
  {
    CtryNm: "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)",
    CurrencyName: "Pound Sterling",
    Ccy: "GBP",
    CcyNbr: "826",
    CcyMnrUnts: "2",
    prefix: "£",
    keyCode: 13,
    countyCode: "en-GB",
  },
  {
    CtryNm: "BANGLADESH",
    CurrencyName: "Taka",
    Ccy: "BDT",
    CcyNbr: "050",
    CcyMnrUnts: "2",
    prefix: "৳",
    keyCode: 5,
    countyCode: "en-BD",
  },
  {
    CtryNm: "TURKEY",
    CurrencyName: "Turkish Lira",
    Ccy: "TRY",
    CcyNbr: "949",
    CcyMnrUnts: "2",
    prefix: "TRY",
    keyCode: 12,
    countyCode: "tr-TR",
  },
  {
    CtryNm: "PUERTO RICO",
    CurrencyName: "US Dollar",
    Ccy: "USD",
    CcyNbr: "840",
    CcyMnrUnts: "2",
    prefix: "$",
    keyCode: 14,
    countyCode: "en-US",
  },
];
export const CountryListInterNational = [
  { countyName: "English", countyCode: "en" },
  { countyName: "Portuguese (Brazil)\t", countyCode: "pt" },
  { countyName: "Portuguese (Portugal)\t", countyCode: "ptPT" },
  { countyName: "Spanish", countyCode: "es" },
  { countyName: "French", countyCode: "fr" },
  { countyName: "Esperanto", countyCode: "eo" },
  { countyName: "Vietnamese", countyCode: "vi" },
  { countyName: "Arabic", countyCode: "ar" },
  { countyName: "Azerbaijan", countyCode: "az" },
  { countyName: "Turkish", countyCode: "tr" },
  { countyName: "English (Indian)\t", countyCode: "enIndian" },
  { countyName: "Ukrainian", countyCode: "uk" },
  { countyName: "Indonesian", countyCode: "id" },
  { countyName: "Russian", countyCode: "ru" },
];
